spring:
  application:
    name: contactos

  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3307/contactos?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  thymeleaf:
    cache: false

server:
  error:
    include-message: always
